name: Test

on:
  push:
    branches: [ master develop ci]
  pull_request:
    branches: [ master ]

jobs:

  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm install . -g
    - name: Run the test
      run: bash test/test.sh
