name: Test

on:
  push:
    branches: [ master develop ci]
  pull_request:
    branches: [ master ]

jobs:

  build:
    
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Run the test
      run: bash test/test.sh
